version: "3.3"
services:

  web:
    build: ./
    image: advertisment/python
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      C_FORCE_ROOT: "yes"
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: advertisment
      POSTGRES_USER: advertisment
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
